version: "3.9"

services:
  backend:
    build: ./app
    container_name: ai-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
